### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by AsyaOrlova** [HUBioDataLab/SELFormer#12]
What do modelO, modelC and modelM refer to in the pre-trained models link?

**Comment by ervau** [comment]
Hi @AsyaOrlova,

Apologies for the confusion regarding the naming of the models. In our paper, we use more descriptive names, but these were not updated in the pre-trained model folder. We have now renamed them to match the names used in the paper to prevent further confusion. You can access the files with the updated names [here](https://drive.google.com/drive/folders/1c3Mwc3j4M0PHk_iORrKU_V5cuxkD9aM6?usp=share_link) or from the README.

To clarify the correspondence between the old and new model names:

- modelM refers to the model with fewer trainable parameters, now named SELFormer-Lite.
- modelO is the larger (default) model, now named SELFormer.
- modelC is similar to modelM in terms of size and performance; therefore, we discarded it.

For more detailed information about the hyperparameters, size, and performance of SELFormer-Lite and SELFormer models, please refer to our paper: https://doi.org/10.1088/2632-2153/acdb30.
