### ISSUE TITLE
The upper limit of molecule encoding

### ISSUE THREAD

**Issue by Kartinaa** [HUBioDataLab/SELFormer#14]
Dear author,

Thank you for sharing your wonderful work! When I was using your model, I attempted to encode approximately 160k SELFIES into latent vectors. However, I found that the model can only handle 100k at a time. I just want to confirm: does this mean that only the first 100k molecules from my SELFIES file are being encoded? Or is there a way to adjust the settings so I can encode all the molecules at once?

Many thanks for your time and appreciate your help!

**Comment by tuncadogan** [comment]
Dear Kartinaa,

Thank you for your interest in SELFormer and your kind words. After your message, we discussed this among developers. It appears that this was just a setting we added during our initial tests and unintentionally left in the official release. We have now removed it and updated the repo. Please let us know if you are still having this or another issue.
