### ISSUE TITLE
Error in generate embeddings for the SELFIES molecule dataset

### ISSUE THREAD

**Issue by mojtabaze7** [HUBioDataLab/SELFormer#2]
Hello.
I want to generate embeddings for my dataset.

I run this command:
```
python3 produce_embeddings.py --selfies_dataset=data/molecule_dataset_selfies.csv --model_file=data/pretrained_models/modelO --embed_file=data/embeddings.csv
```

but there is an error:
OSError: Can't load the configuration of 'data/pretrained_models/modelO'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'data/pretrained_models/modelO' is the correct path to a directory containing a config.json file

How to resolve this error?

**Comment by ervau** [comment]
Hi @mojtabaze7, the error message indicates that the path given to the --model_file argument may be incorrect or incomplete. produce_embeddings.py script is unable to load the configuration of the model from the specified path. To resolve this error, please make sure that the path given to the --model_file argument is correct and points to the directory containing the model's config.json file.

**Comment by mojtabaze7** [comment]
Can you share link of the pretrained model to use in generating embeddings?

**Comment by ervau** [comment]
You can use [this link](https://drive.google.com/file/d/1zuVAKXCMc-HZHQo9y3Hu5zmQy51FGduI/view?usp=sharing) to download the pre-trained models. I suggest referring to the README file, as it provides all the necessary links for models and pre-generated embeddings, along with detailed instructions on how to use these resources.
